http://localhost:8080/locations/barra da tijuca



###
http://localhost:8080/listings/abc/abc/Rio de Janeiro/BR>Rio de Janeiro>NULL>Rio de Janeiro>Zona Oeste>Barra da Tijuca/Barra da Tijuca/Rio de Janeiro/RJ/Zona Oeste



###
http://localhost:8080/listings/RENTAL/USED/Rio de Janeiro/BR>Rio de Janeiro>NULL>Rio de Janeiro>Zona Oeste>Barra da Tijuca/Barra da Tijuca/Rio de Janeiro/RJ/Zona Oeste

